apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
type: Opaque
data:
  OPENAI_API_KEY: c2stcHJvai0xSGxBNU1QVUtybWUxbmdsQlJSUkM4YmI3NGhoejFfMGlJQnFWSksyT0R4S1VtMlZRLW10d3NMMEVOTlptbWtoLVBCU2JkM042LVQzQmxia0ZKLXlHWWk2TXFjak0xaGFnSHJoTHV2czg1U0JUX2puOFN0OHhPeXJJSFFVcXZOV2w3a3FoN2RLUmJKcHNJQlVfU2M0ODlHeHptUUE=
